Controllers/DatTiecKhachController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebNC.Common;
using WebNC.Models;

namespace WebNC.Controllers
{
    public class DatTiecKhachController : BaseController
    {
        private CSDLContext db = new CSDLContext();

        // GET: DatTiecKhach
        public ActionResult Index()
        {
            var user = (KhachHang)Session[Constant.USER_INFO];
            var datTiecs = db.DatTiecs.Include(d => d.DichVu).Include(d => d.KhachHang).Include(d => d.Menu).Include(d => d.Sanh).Where(x => x.KhachID == user.KhachID);
            return View(datTiecs.ToList());
        }

        public ActionResult Searching(string ten)
        {
            var dattiec = db.DatTiecs.Where(x => x.ChuRe.Contains(ten) || x.CoDau.Contains(ten)).ToList();
            return View("Index", dattiec);
        }

        // GET: DatTiecKhach/Create
        public ActionResult Create()
        {
            ViewBag.Sanh = db.Sanhs.OrderBy(x=>x.TenSanh).ToList();
            ViewBag.DichVu = db.DichVus.OrderBy(x => x.TenDichVu).ToList();
            ViewBag.MonAn = db.MonAns.OrderBy(x => x.TenMonAn).ToList();
            ViewBag.Menu = db.Menus.OrderBy(x => x.TenMenu).ToList();
            //ViewBag.KhachID = new SelectList(db.KhachHangs, "KhachID", "TenKhach");
            //ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "TenMenu");
            //ViewBag.SanhID = new SelectList(db.Sanhs, "SanhID", "TenSanh");
            return View();
        }

        // POST: DatTiecKhach/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TiecID,ChuRe,CoDau,NgayDat,SoBan,GiaTiec,MenuID,SanhID,KhachID,DichVuID")] DatTiec datTiec)
        {
            if (ModelState.IsValid)
            {
                var sum = db.MonAns.ToList().Where(x => x.MenuID == datTiec.MenuID).Sum(x => x.GiaMonAn);
                var dichvu = db.DichVus.ToList().SingleOrDefault(x => x.DichVuID == datTiec.DichVuID);
                datTiec.GiaTiec = (sum * datTiec.SoBan)+dichvu.GiaDichVu;
                db.DatTiecs.Add(datTiec);

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            ViewBag.DichVuID = new SelectList(db.DichVus, "DichVuID", "TenDichVu", datTiec.DichVuID);
            ViewBag.KhachID = new SelectList(db.KhachHangs, "KhachID", "TenKhach", datTiec.KhachID);
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "TenMenu", datTiec.MenuID);
            ViewBag.SanhID = new SelectList(db.Sanhs, "SanhID", "TenSanh", datTiec.SanhID);
            return View(datTiec);
        }

        // GET: DatTiecKhach/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatTiec datTiec = db.DatTiecs.Find(id);
            if (datTiec == null)
            {
                return HttpNotFound();
            }
            ViewBag.DichVuID = new SelectList(db.DichVus, "DichVuID", "TenDichVu", datTiec.DichVuID);
            ViewBag.KhachID = new SelectList(db.KhachHangs, "KhachID", "TenKhach", datTiec.KhachID);
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "TenMenu", datTiec.MenuID);
            ViewBag.SanhID = new SelectList(db.Sanhs, "SanhID", "TenSanh", datTiec.SanhID);
            return View(datTiec);
        }

        // POST: DatTiecKhach/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TiecID,ChuRe,CoDau,NgayDat,SoBan,GiaTiec,MenuID,SanhID,KhachID,DichVuID")] DatTiec datTiec)
        {
            if (ModelState.IsValid)
            {
                db.Entry(datTiec).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DichVuID = new SelectList(db.DichVus, "DichVuID", "TenDichVu", datTiec.DichVuID);
            ViewBag.KhachID = new SelectList(db.KhachHangs, "KhachID", "TenKhach", datTiec.KhachID);
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "TenMenu", datTiec.MenuID);
            ViewBag.SanhID = new SelectList(db.Sanhs, "SanhID", "TenSanh", datTiec.SanhID);
            return View(datTiec);
        }

        // GET: DatTiecKhach/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatTiec datTiec = db.DatTiecs.Find(id);
            if (datTiec == null)
            {
                return HttpNotFound();
            }
            return View(datTiec);
        }

        // POST: DatTiecKhach/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DatTiec datTiec = db.DatTiecs.Find(id);
            db.DatTiecs.Remove(datTiec);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/KhachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebNC.Models;

namespace WebNC.Controllers
{
    public class KhachController : Controller
    {
        private CSDLContext db = new CSDLContext();

        // GET: Khach
        public ActionResult Index()
        {
            return View(db.Sanhs.OrderBy(x => x.TenSanh).ToList());
        }

        public ActionResult ThucDon()
        {
            var monAns = db.MonAns;
            return View(monAns.ToList());
        }
        public ActionResult DichVu()
        {
            return View(db.DichVus.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KhachID,TenKhach,SDT,DiaChi,Email,Username,Password")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                db.KhachHangs.Add(khachHang);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            return View(khachHang);
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebNC.Common;
using WebNC.Models;

namespace WebNC.Controllers
{
    public class LoginController : Controller
    {
        private CSDLContext db = new CSDLContext();
        // GET: Login
        public ActionResult Index()
        {
            Session[Constant.USER_INFO] = null;
            Session[Constant.USER] = null;
            return View();
        }
        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            try
            {
                if (username == "admin")
                {
                    if (password == "admin")
                    {
                        var usersession = new Login();
                        usersession.Username = username;
                        usersession.Password = password;
                        Session.Add(Constant.USER, usersession);
                        var kh = db.KhachHangs.SingleOrDefault(x => x.Username == username);
                        Session[Constant.USER_INFO] = kh;
                        return RedirectToAction("Index", "Sanh", new { area = "Admin" });
                    }
                    else
                    {
                        return View("Index");
                    }
                }
                var khachang = db.KhachHangs.SingleOrDefault(x => x.Username == username);
                Session[Constant.USER_INFO] = khachang;
                if (khachang == null)
                {
                    return View("Index");
                }
                else
                {
                    if (khachang.Password == password)
                    {
                        var usersession = new Login();
                        usersession.Username = username;
                        usersession.Password = password;

                        Session.Add(Constant.USER, usersession);
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        return View("Index");
                    }
                }
            }
            catch
            {
                return View("Index");
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - K&H Venue</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/fontawesome")
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/fontawesome/font-awesome.min.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/0c347a59c7.js" crossorigin="anonymous"></script>
</head>
<body style="padding-top:75px">
    <nav class="navbar navbar-expand-sm navbar-light fixed-top" style="background-color:#d9b08c">
        <a class="navbar-brand" href="#">
            <img style="height:50px;width:150px" src="~/Content/Images/top.png" />
        </a>

        <ul class="navbar-nav mx-auto">
            <li class="nav-item"><a href=@Url.Action("Index", "Home") class="nav-link">TRANG CHỦ</a></li>
            <li class="nav-item"><a href=@Url.Action("About", "Home") class="nav-link">GIỚI THỆU</a></li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    TIỆC CƯỚI
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href=@Url.Action("Index", "DatTiecKhach")>ĐẶT TIỆC CƯỚI</a>
                    <a class="dropdown-item" href=@Url.Action("Index", "Khach")>SẢNH TIỆC</a>
                    <a class="dropdown-item" href=@Url.Action("ThucDon", "Khach")>THỰC ĐƠN</a>
                </div>
            </li>

            <li class="nav-item"><a href=@Url.Action("DichVu", "Khach") class="nav-link">DỊCH VỤ</a></li>
            <li class="nav-item"><a href=@Url.Action("Contact", "Home") class="nav-link">LIÊN HỆ</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right" style="padding-top:10px">
            @if (Session[WebNC.Common.Constant.USER] == null)

            {
                <li><a href=@Url.Action("Create", "Khach")><i class="fas fa-user-plus"></i>Đăng ký</a></li>
                <p style="margin-left:10px;margin-right:10px">| </p>
                <li><a href=@Url.Action("Index", "Login")><i class="fas fa-sign-in-alt"></i>Đăng nhập</a></li>
            }
            else
            {
                var khachhang = (WebNC.Models.KhachHang)Session[WebNC.Common.Constant.USER_INFO];
                <p style="margin-right:5px">Xin chào,</p>
                <li>@khachhang.TenKhach</li>
                <p style="margin-left:10px;margin-right:10px">|</p>
                <li><a href=@Url.Action("Index", "Login")><i class="fas fa-sign-out-alt"></i>Đăng xuất</a></li>
            }
        </ul>
    </nav>
    <div class="container-fluid">
        @RenderBody()
        <hr />
        <footer style="background-color:#744025;height:auto;color:white">
            <div class="container body-content">
                <div class="row">
                    <div class="col-sm-6">
                        <h2><b>K&H VENUE</b></h2>
                        <p>Hotline: 0929066331 | 0387777253</p>
                        <p>Email: nhochamvui5@gmail.com | luchihao253@gmail.com</p>
                        <p>Địa chỉ: 155 Sư Vạn Hạnh (nối dài), P13, Q.10, TP.HCM</p>
                        <p><i class="fab fa-twitter-square"></i><a href="https://twitter.com/" style="color:white;margin-left:5px">K&H Venue - Twitter</a></p>
                        <p><i class="fa fa-facebook-official"></i><a href="https://www.facebook.com/" style="color:white;margin-left:5px">K&H Venue - Facebook</a></p>
                    </div>
                    <div class="col-sm-6" style="margin-top:20px">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.4602324215048!2d106.66521371480079!3d10.776019492321794!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752edba026cb75%3A0xb2a9aab49da1c58f!2zMTU1IFPGsCBW4bqhbiBI4bqhbmgsIFBoxrDhu51uZyAxMiwgUXXhuq1uIDEwLCBI4buTIENow60gTWluaA!5e0!3m2!1svi!2s!4v1594818717077!5m2!1svi!2s" width="600" height="250" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Styles.Render("~/Content/fontawesome/font-awesome.min.css")
</body>
</html>