Models/DatTiec.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Security.Policy;
using System.Web;

namespace WebNC.Models
{
    public class DatTiec
    {
        [Key]
        public int TiecID { get; set; }
        [Required]
        [DisplayName("Tên Chú rể")]
        public string ChuRe { get; set; }
        [Required]
        [DisplayName("Tên Cô dâu")]
        public string CoDau { get; set; }
        [DisplayName("Ngày đặt")]
        public DateTime NgayDat { get; set; }
        [Required]
        [DisplayName("Số bàn")]
        [Range(1,999)]
        public int SoBan { get; set; }
        [DisplayName("Giá tiệc")]
        public int GiaTiec { get; set; }
        [ForeignKey("Menu")]
        public int MenuID { get; set; }
        public virtual Menu Menu { get; set; }
        [ForeignKey("Sanh")]
        public int SanhID { get; set; }
        public virtual Sanh Sanh{ get; set; }
        [ForeignKey("KhachHang")]
        public int KhachID { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [ForeignKey("DichVu")]
        public int DichVuID { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}

Areas/Admin/Controllers/DatTiecController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebNC.Controllers;
using WebNC.Models;

namespace WebNC.Areas.Admin.Controllers
{
    public class DatTiecController : BaseController
    {
        private CSDLContext db = new CSDLContext();

        // GET: Admin/DatTiec
        public ActionResult Index()
        {
            var datTiecs = db.DatTiecs.Include(d => d.DichVu).Include(d => d.KhachHang).Include(d => d.Menu).Include(d => d.Sanh);
            return View(datTiecs.ToList());
        }

        public ActionResult Searching(string ten)
        {
            var dattiec = db.DatTiecs.Where(x => x.ChuRe.Contains(ten) || x.CoDau.Contains(ten)).ToList();
            return View("Index", dattiec);
        }

        // GET: Admin/DatTiec/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatTiec datTiec = db.DatTiecs.Find(id);
            if (datTiec == null)
            {
                return HttpNotFound();
            }
            return View(datTiec);
        }

        // GET: Admin/DatTiec/Create
        public ActionResult Create()
        {
            ViewBag.KhachID = new SelectList(db.KhachHangs, "KhachID", "TenKhach");
            ViewBag.Sanh = db.Sanhs.OrderBy(x => x.TenSanh).ToList();
            ViewBag.DichVu = db.DichVus.OrderBy(x => x.TenDichVu).ToList();
            ViewBag.MonAn = db.MonAns.OrderBy(x => x.TenMonAn).ToList();
            ViewBag.Menu = db.Menus.OrderBy(x => x.TenMenu).ToList();
            return View();
        }

        // POST: Admin/DatTiec/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TiecID,ChuRe,CoDau,NgayDat,SoBan,GiaTiec,MenuID,SanhID,KhachID,DichVuID")] DatTiec datTiec)
        {
            if (ModelState.IsValid)
            {
                var sum = db.MonAns.ToList().Where(x => x.MenuID == datTiec.MenuID).Sum(x => x.GiaMonAn);
                var dichvu = db.DichVus.ToList().SingleOrDefault(x => x.DichVuID == datTiec.DichVuID);
                datTiec.GiaTiec = (sum * datTiec.SoBan) + dichvu.GiaDichVu;
                db.DatTiecs.Add(datTiec);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DichVuID = new SelectList(db.DichVus, "DichVuID", "TenDichVu", datTiec.DichVuID);
            ViewBag.KhachID = new SelectList(db.KhachHangs, "KhachID", "TenKhach", datTiec.KhachID);
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "TenMenu", datTiec.MenuID);
            ViewBag.SanhID = new SelectList(db.Sanhs, "SanhID", "TenSanh", datTiec.SanhID);
            return View(datTiec);
        }

        // GET: Admin/DatTiec/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatTiec datTiec = db.DatTiecs.Find(id);
            if (datTiec == null)
            {
                return HttpNotFound();
            }
            ViewBag.DichVuID = new SelectList(db.DichVus, "DichVuID", "TenDichVu", datTiec.DichVuID);
            ViewBag.KhachID = new SelectList(db.KhachHangs, "KhachID", "TenKhach", datTiec.KhachID);
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "TenMenu", datTiec.MenuID);
            ViewBag.SanhID = new SelectList(db.Sanhs, "SanhID", "TenSanh", datTiec.SanhID);
            return View(datTiec);
        }

        // POST: Admin/DatTiec/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TiecID,ChuRe,CoDau,NgayDat,SoBan,GiaTiec,MenuID,SanhID,KhachID,DichVuID")] DatTiec datTiec)
        {
            if (ModelState.IsValid)
            {
                var sum = db.MonAns.ToList().Where(x => x.MenuID == datTiec.MenuID).Sum(x => x.GiaMonAn);
                var dichvu = db.DichVus.ToList().SingleOrDefault(x => x.DichVuID == datTiec.DichVuID);
                datTiec.GiaTiec = (sum * datTiec.SoBan) + dichvu.GiaDichVu;
                db.Entry(datTiec).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DichVuID = new SelectList(db.DichVus, "DichVuID", "TenDichVu", datTiec.DichVuID);
            ViewBag.KhachID = new SelectList(db.KhachHangs, "KhachID", "TenKhach", datTiec.KhachID);
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "TenMenu", datTiec.MenuID);
            ViewBag.SanhID = new SelectList(db.Sanhs, "SanhID", "TenSanh", datTiec.SanhID);
            return View(datTiec);
        }

        // GET: Admin/DatTiec/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatTiec datTiec = db.DatTiecs.Find(id);
            if (datTiec == null)
            {
                return HttpNotFound();
            }
            return View(datTiec);
        }

        // POST: Admin/DatTiec/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DatTiec datTiec = db.DatTiecs.Find(id);
            db.DatTiecs.Remove(datTiec);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/DatTiec/Create.cshtml
@model WebNC.Models.DatTiec
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section scripts{
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>
        $(function () {
            $(".datepicker").datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true
            });

        });
    </script>
}
@{
    var dichvu = (List<WebNC.Models.DichVu>)ViewBag.DichVu;
    var sanh = (List<WebNC.Models.Sanh>)ViewBag.Sanh;
    var monan = (List<WebNC.Models.MonAn>)ViewBag.MonAn;
    var menu = (List<WebNC.Models.Menu>)ViewBag.Menu;
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="padding-top:20px;text-align:center">ĐẶT TIỆC</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container body-content" style="padding-left:100px;padding-right:100px">
        <div class="form-horizontal">
            <hr />

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.KhachID, "Tên Khách hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("KhachID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.KhachID, "", new { @class = "text-danger" })
                </div>
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ChuRe, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ChuRe, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ChuRe, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CoDau, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CoDau, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CoDau, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                    @Html.LabelFor(model => model.MenuID, "MenuID", htmlAttributes: new { @class = "control-label col-md-2" })

                    <div class="col-md-10">
                        @Html.DropDownList("MenuID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MenuID, "", new { @class = "text-danger" })
                    </div>
                </div>*@

            <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
            <select name="MenuID" id="menu" class="menu" style="margin-left:15px">
                @for (int i = 0; i < menu.Count; i++)
                {
                    var monanbymenu = monan.Where(x => x.MenuID == menu[i].MenuID).ToList();
                    for (int j = 0; j < monanbymenu.Count; j++)
                    {
                        <option value="@menu[i].MenuID" data-gia="@monan[j].GiaMonAn" data-ten="@monan[j].TenMonAn" selected>@menu[i].TenMenu</option>
                    }
                }
            </select>
            <br />
            <p style="margin-left:15px" class="tenmon">
            <p style="margin-left:15px" class="giamon">
                <script>
                    $(function () {
                        $(".menu").on('change', function (i) {
                            $(this).siblings(".tenmon").text('Món: ' + $(this).find(":selected").attr("data-ten"));
                            $(this).siblings(".giamon").text('Giá: ' + $(this).find(":selected").attr("data-gia"));
                        });
                    });
                </script>
                <div class="form-group">
                    @Html.LabelFor(model => model.SoBan, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SoBan, new { htmlAttributes = new { @min = "1", @max = "100", type = "number", @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SoBan, "", new { @class = "text-danger" })
                    </div>
                </div>
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
                <select name="SanhID" id="sanh" class="sanh" style="margin-left:15px">
                    @for (int i = 0; i < sanh.Count; i++)
                    {
                        <option value="@sanh[i].SanhID" data-src="/Content/Images/Sanh/@sanh[i].HinhSanh" selected>@sanh[i].TenSanh</option>

                    }
                </select>
                <br />
                <img class="item_thumb" src="~/Content/Images/Sanh/sanh5(202068193056845).jpg" style="height:500px;width:900px;margin-left:15px" />

                <script>
                    $(function () {
                        $(".sanh").on('change', function () {
                            $(this).siblings(".item_thumb").attr("src", $(this).find(":selected").attr("data-src"));
                        });

                    });
                </script>



                <div class="form-group">
                    @Html.LabelFor(model => model.NgayDat, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NgayDat, new { htmlAttributes = new { @class = "datepicker" } })
                        @Html.ValidationMessageFor(model => model.NgayDat, "", new { @class = "text-danger" })
                    </div>
                </div>

                <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
                @Html.LabelFor(model => model.DichVuID, "Dịch vụ", htmlAttributes: new { @class = "control-label col-md-2" })
                <br />
                <select name="DichVuID" id="dichvu" class="dichvu" style="margin-left:15px">
                    @for (int i = 0; i < dichvu.Count; i++)
                    {
                        <option value="@dichvu[i].DichVuID" data-src="/Content/Images/DichVu/@dichvu[i].HinhDichVu" data="@dichvu[i].GiaDichVu" selected>@dichvu[i].TenDichVu</option>
                    }
                </select>
                <br />
                <img class="itemdichvu_thumb" src="~/Content/Images/DichVu/thapruou(2020717192421693).jpg" style="height:500px;width:950px;margin-left:15px" />
            <p class="giadichvu" style="margin-left:15px">
                <script>
                    $(function () {
                        $(".dichvu").on('change', function () {
                            $(this).siblings(".itemdichvu_thumb").attr("src", $(this).find(":selected").attr("data-src"));
                            $(this).siblings(".giadichvu").text('Giá: ' + $(this).find(":selected").attr("data"));
                        });
                    });
                </script>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-info" style="background-color:#d9b08c" value="Đặt tiệc" />
                <br />
                @Html.ActionLink("Trở về", "Index")
            </div>
        </div>
    </div>
}

Areas/Admin/Views/DatTiec/Delete.cshtml
@model WebNC.Models.DatTiec

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>HỦY TIỆC</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DichVu.TenDichVu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DichVu.TenDichVu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KhachHang.TenKhach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhachHang.TenKhach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Menu.TenMenu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Menu.TenMenu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sanh.TenSanh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sanh.TenSanh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChuRe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChuRe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoDau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoDau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayDat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaTiec)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaTiec)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" class="btn btn-info" style="background-color:#d9b08c" value="Hủy" /> |
            @Html.ActionLink("Trở về", "Index")
        </div>
    }

</div>

Areas/Admin/Views/DatTiec/Details.cshtml
@model WebNC.Models.DatTiec

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>DatTiec</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DichVu.TenDichVu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DichVu.TenDichVu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KhachHang.TenKhach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhachHang.TenKhach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Menu.TenMenu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Menu.TenMenu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sanh.TenSanh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sanh.TenSanh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChuRe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChuRe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoDau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoDau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayDat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaTiec)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaTiec)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TiecID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Areas/Admin/Views/DatTiec/Edit.cshtml
@model WebNC.Models.DatTiec

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>THAY ĐỔI THÔNG TIN</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.TiecID)

    <div class="form-group">
        @Html.LabelFor(model => model.KhachID, "Tên Khách hàng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("KhachID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.KhachID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ChuRe, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ChuRe, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ChuRe, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CoDau, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CoDau, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CoDau, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MenuID, "Thực đơn", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MenuID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MenuID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SanhID, "Sảnh", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("SanhID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SanhID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoBan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoBan, new { htmlAttributes = new { @min = "1", @max = "100", type = "number", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoBan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayDat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NgayDat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayDat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DichVuID, "Dịch vụ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DichVuID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DichVuID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-info" style="background-color:#d9b08c" value="Lưu" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

Areas/Admin/Views/DatTiec/Index.cshtml
@model IEnumerable<WebNC.Models.DatTiec>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-align:center">QUẢN LÝ TIỆC CƯỚI</h2>
<form action="@Url.Action("Searching","DatTiec")" style="text-align:right;padding-bottom:20px">
    <label>Tên Chú rể hoặc Cô dâu:</label>
    <input name="ten" class="form-control" style="display:inline" />
    <input id="search" type="submit" class="btn btn-info" style="background-color:#d9b08c" value="Tìm" />
</form>
<table class="table" style="text-align:center">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.KhachHang.TenKhach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ChuRe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CoDau)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Menu.TenMenu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sanh.TenSanh)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.NgayDat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DichVu.TenDichVu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GiaTiec)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.KhachHang.TenKhach)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChuRe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CoDau)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Menu.TenMenu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sanh.TenSanh)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.NgayDat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DichVu.TenDichVu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoBan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaTiec)
            </td>
            <td>
                <input type="button" class="btn btn-info" style="background-color:#d9b08c" value="Đổi" onclick="location.href='@Url.Action("Edit", "DatTiec", new { id = item.TiecID })'" />
                <input type="button" class="btn btn-info" style="background-color:#d9b08c" value="Hủy" onclick="location.href='@Url.Action("Delete", "DatTiec", new { id = item.TiecID })'" />
            </td>
        </tr>
    }

</table>
<div class="container" style="text-align:right">
    <input type="button" class="btn btn-info" style="background-color:#d9b08c" value="Đặt tiệc" onclick="location.href='@Url.Action("Create", "DatTiec")'" />
</div>