Models/MonAn.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Dynamic;
using System.Linq;
using System.Web;

namespace WebNC.Models
{
    public class MonAn
    {
        [Key]
        public int MonAnID { get; set; }
        [Required]
        [DisplayName("Tên món")]
        public string TenMonAn { get; set; }
        [Required]
        [DisplayName("Giá")]
        public int GiaMonAn { get; set; }
        [DisplayName("Hình ảnh")]
        public string HinhMonAn { get; set; }
        [ForeignKey("Menu")]
        
        public Nullable<int> MenuID { get; set; }
        public virtual Menu Menu { get; set; }
    }
}

Areas/Admin/Controllers/MonAnController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebNC.Controllers;
using WebNC.Models;

namespace WebNC.Areas.Admin.Controllers
{
    public class MonAnController : BaseController
    {
        private CSDLContext db = new CSDLContext();

        // GET: Admin/MonAn
        public ActionResult Index()
        {
            ViewBag.MENU = db.Menus.ToList();
            var monAns = db.MonAns.Include(m => m.Menu);
            return View(monAns.ToList());
        }
        public ActionResult Searching(string tenmon, int menu)
        {
            var monan = db.MonAns.Where(x => x.MenuID == menu && x.TenMonAn.Contains(tenmon)).ToList();
            ViewBag.MENU = db.Menus.ToList();
            return View("Index",monan);
        }

        // GET: Admin/MonAn/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonAn monAn = db.MonAns.Find(id);
            if (monAn == null)
            {
                return HttpNotFound();
            }
            return View(monAn);
        }

        // GET: Admin/MonAn/Create
        public ActionResult Create()
        {
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "TenMenu");
            return View();
        }

        // POST: Admin/MonAn/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MonAnID,TenMonAn,GiaMonAn,HinhMonAn,MenuID")] MonAn monAn, HttpPostedFileBase postedFile)
        {
            if (ModelState.IsValid)
            {
                string filename = Path.GetFileName(postedFile.FileName);
                string fullfilename = filename.Split('.')[0] + "(" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString() + DateTime.Now.Day.ToString() + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + DateTime.Now.Second.ToString() + DateTime.Now.Millisecond.ToString() + ")." + filename.Split('.')[1];
                string path = Path.Combine(Server.MapPath("~/Content/Images/MonAn"), fullfilename);
                postedFile.SaveAs(path);
                monAn.HinhMonAn = fullfilename;
                db.MonAns.Add(monAn);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "TenMenu", monAn.MenuID);
            return View(monAn);
        }

        // GET: Admin/MonAn/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonAn monAn = db.MonAns.Find(id);
            if (monAn == null)
            {
                return HttpNotFound();
            }
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "TenMenu", monAn.MenuID);
            return View(monAn);
        }

        // POST: Admin/MonAn/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MonAnID,TenMonAn,GiaMonAn,HinhMonAn,MenuID")] MonAn monAn, HttpPostedFileBase postedFile)
        {
            if (ModelState.IsValid)
            {
                if (postedFile != null)
                {
                    string filename = Path.GetFileName(postedFile.FileName);
                    string fullfilename = filename.Split('.')[0] + "(" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString() + DateTime.Now.Day.ToString() + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + DateTime.Now.Second.ToString() + DateTime.Now.Millisecond.ToString() + ")." + filename.Split('.')[1];
                    string path = Path.Combine(Server.MapPath("~/Content/Images/MonAn"), fullfilename);
                    postedFile.SaveAs(path);
                    monAn.HinhMonAn = fullfilename;
                }
                db.Entry(monAn).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "TenMenu", monAn.MenuID);
            return View(monAn);
        }

        // GET: Admin/MonAn/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonAn monAn = db.MonAns.Find(id);
            if (monAn == null)
            {
                return HttpNotFound();
            }
            return View(monAn);
        }

        // POST: Admin/MonAn/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MonAn monAn = db.MonAns.Find(id);
            db.MonAns.Remove(monAn);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/MonAn/Create.cshtml
@model WebNC.Models.MonAn

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>THÊM MÓN ĂN</h2>

@using (Html.BeginForm("Create", "MonAn", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenMonAn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenMonAn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenMonAn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaMonAn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaMonAn, new { htmlAttributes = new { @min = "1", type = "number", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaMonAn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhMonAn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("postedFile", "", new { @class = "input-file", type = "file" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuID, "Thực đơn", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MenuID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MenuID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-info" style="background-color:#d9b08c" value="Thêm" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

Areas/Admin/Views/MonAn/Delete.cshtml
@model WebNC.Models.MonAn

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>XÓA MÓN ĂN</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            <b style="font-size:24px">@Html.DisplayFor(model => model.TenMonAn)</b>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaMonAn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GiaMonAn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Menu.TenMenu)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Menu.TenMenu)
        </dd>
        <dd>
            <img src="~/Content/Images/MonAn/@Model.HinhMonAn" class="img-thumbnail" style="width: 300px;height: 200px" />
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" class="btn btn-info" style="background-color:#d9b08c" value="Xóa" /> |
            @Html.ActionLink("Trở về", "Index")
        </div>
    }

</div>

Areas/Admin/Views/MonAn/Details.cshtml
@model WebNC.Models.MonAn

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>CHI TIẾT MÓN ĂN</h2>

<div>
        <hr />
        <dl class="dl-horizontal">
            <dd>
                <b style="font-size:24px">@Html.DisplayFor(model => model.TenMonAn)</b>
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GiaMonAn)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.GiaMonAn)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Menu.TenMenu)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Menu.TenMenu)
            </dd>
            <dd>
                <img src="~/Content/Images/MonAn/@Model.HinhMonAn" class="img-thumbnail" style="width: 300px;height: 200px" />
            </dd>
        </dl>
</div>
<p>
    @Html.ActionLink("Trở về", "Index")
</p>

Areas/Admin/Views/MonAn/Edit.cshtml
@model WebNC.Models.MonAn

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>THAY ĐỔI CHI TIẾT MÓN ĂN</h2>

@using (Html.BeginForm("Edit", "MonAn", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MonAnID)

    <div class="form-group">
        @Html.LabelFor(model => model.TenMonAn, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenMonAn, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenMonAn, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaMonAn, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaMonAn, new { htmlAttributes = new { @min = "1", type = "number", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaMonAn, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HinhMonAn, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <img src="~/Content/Images/MonAn/@Model.HinhMonAn" style="height:120px; width:auto;" />
            @Html.TextBox("postedFile", "", new { @class = "input-file", type = "file" })
        </div>
    </div>
    <input hidden value="@Model.HinhMonAn" name="HinhMonAn" />

    <div class="form-group">
        @Html.LabelFor(model => model.MenuID, "Thực đơn", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MenuID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MenuID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-info" style="background-color:#d9b08c" value="Lưu" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

Areas/Admin/Views/MonAn/Index.cshtml
@model IEnumerable<WebNC.Models.MonAn>
@using WebNC.Models;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var MENU = (List<Menu>)ViewBag.MENU;
}

<h2 style="text-align:center">QUẢN LÝ MÓN ĂN</h2>

<form action="@Url.Action("Searching","MonAn")">
    <label>Tên món:</label>
    <input name="tenmon" class="form-control" />
    <label>Thực đơn:</label>
    <select name="menu" class="form-control">
        @for (int i = 0; i < MENU.Count; i++)
        {
            <option value="@MENU[i].MenuID">@MENU[i].TenMenu</option>
        }
    </select>
    <input id="search" type="submit" class="btn btn-info" style="background-color:#d9b08c;margin-bottom:10px;margin-top:5px" value="Tìm" />
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenMonAn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GiaMonAn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HinhMonAn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Menu.TenMenu)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.TenMonAn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaMonAn)
            </td>
            <td>
                <img src="~/Content/Images/MonAn/@item.HinhMonAn" class="img-thumbnail" style="width:300px; height:200px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Menu.TenMenu)
            </td>
            <td>
                <input type="button" class="btn btn-info" style="background-color:#d9b08c" value="Sửa" onclick="location.href='@Url.Action("Edit", "MonAn", new { id = item.MonAnID })'" />
                <input type="button" class="btn btn-info" style="background-color:#d9b08c" value="Chi tiết" onclick="location.href='@Url.Action("Details", "MonAn", new { id = item.MonAnID })'" />
                <input type="button" class="btn btn-info" style="background-color:#d9b08c" value="Xóa" onclick="location.href='@Url.Action("Delete", "MonAn", new { id = item.MonAnID })'" />
            </td>
        </tr>
    }

</table>
<div class="container" style="text-align:right">
    <input type="button" class="btn btn-info" style="background-color:#d9b08c" value="Thêm món" onclick="location.href='@Url.Action("Create", "MonAn")'" />
</div>