Models/DichVu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebNC.Models
{
    public class DichVu
    {
        [Key]
        public int DichVuID { get; set; }
        [Required]
        [DisplayName("Tên dịch vụ")]
        public string TenDichVu { get; set; }
        [Required]
        [DisplayName("Thông tin")]
        public string HinhThuc { get; set; }
        [Required]
        [DisplayName("Giá dịch vụ")]
        public int GiaDichVu { get; set; }
        [DisplayName("Hình ảnh")]
        public string HinhDichVu { get; set; }
    }
}

Areas/Admin/Controllers/DichVuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebNC.Controllers;
using WebNC.Models;

namespace WebNC.Areas.Admin.Controllers
{
    public class DichVuController : BaseController
    {
        private CSDLContext db = new CSDLContext();

        // GET: Admin/DichVu
        public ActionResult Index()
        {
            return View(db.DichVus.ToList());
        }

        public ActionResult Searching(string tendichvu)
        {
            var dichvu = db.DichVus.Where(x => x.TenDichVu.Contains(tendichvu)).ToList();
            return View("Index", dichvu);
        }

        // GET: Admin/DichVu/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DichVu dichVu = db.DichVus.Find(id);
            if (dichVu == null)
            {
                return HttpNotFound();
            }
            return View(dichVu);
        }

        // GET: Admin/DichVu/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/DichVu/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DichVuID,TenDichVu,HinhThuc,GiaDichVu,HinhDichVu")] DichVu dichVu, HttpPostedFileBase postedFile)
        {
            if (ModelState.IsValid)
            {
                string filename = Path.GetFileName(postedFile.FileName);
                string fullfilename = filename.Split('.')[0] + "(" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString() + DateTime.Now.Day.ToString() + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + DateTime.Now.Second.ToString() + DateTime.Now.Millisecond.ToString() + ")." + filename.Split('.')[1];
                string path = Path.Combine(Server.MapPath("~/Content/Images/DichVu"), fullfilename);
                postedFile.SaveAs(path);
                dichVu.HinhDichVu = fullfilename;
                db.DichVus.Add(dichVu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dichVu);
        }

        // GET: Admin/DichVu/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DichVu dichVu = db.DichVus.Find(id);
            if (dichVu == null)
            {
                return HttpNotFound();
            }
            return View(dichVu);
        }

        // POST: Admin/DichVu/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DichVuID,TenDichVu,HinhThuc,GiaDichVu,HinhDichVu")] DichVu dichVu, HttpPostedFileBase postedFile)
        {
            if (ModelState.IsValid)
            {
                if (postedFile != null)
                {
                    string filename = Path.GetFileName(postedFile.FileName);
                    string fullfilename = filename.Split('.')[0] + "(" + DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString() + DateTime.Now.Day.ToString() + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + DateTime.Now.Second.ToString() + DateTime.Now.Millisecond.ToString() + ")." + filename.Split('.')[1];
                    string path = Path.Combine(Server.MapPath("~/Content/Images/DichVu"), fullfilename);
                    postedFile.SaveAs(path);
                    dichVu.HinhDichVu = fullfilename;
                }
                db.Entry(dichVu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dichVu);
        }

        // GET: Admin/DichVu/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DichVu dichVu = db.DichVus.Find(id);
            if (dichVu == null)
            {
                return HttpNotFound();
            }
            return View(dichVu);
        }

        // POST: Admin/DichVu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DichVu dichVu = db.DichVus.Find(id);
            db.DichVus.Remove(dichVu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/DichVu/Create.cshtml
@model WebNC.Models.DichVu

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>THÊM DỊCH VỤ</h2>
@using (Html.BeginForm("Create", "DichVu", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenDichVu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDichVu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDichVu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhThuc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhThuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HinhThuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaDichVu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaDichVu, new { htmlAttributes = new { @min = "1", type = "number", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaDichVu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhDichVu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("postedFile", "", new { @class = "input-file", type = "file" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-info" style="background-color:#d9b08c" value="Thêm" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

Areas/Admin/Views/DichVu/Delete.cshtml
@model WebNC.Models.DichVu

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>XÓA DỊCH VỤ</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            <b style="font-size:24px">@Html.DisplayFor(model => model.TenDichVu)</b>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaDichVu)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GiaDichVu)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HinhThuc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HinhThuc)
        </dd>
        <dd>
            <img src="~/Content/Images/DichVu/@Model.HinhDichVu" class="img-thumbnail" style="width: 300px;height: 200px" />
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" class="btn btn-info" style="background-color:#d9b08c" value="Xóa" /> |
            @Html.ActionLink("Trở về", "Index")
        </div>
    }

</div>

Areas/Admin/Views/DichVu/Details.cshtml
@model WebNC.Models.DichVu

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>CHI TIẾT DỊCH VỤ</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            <b style="font-size:24px">@Html.DisplayFor(model => model.TenDichVu)</b>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaDichVu)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GiaDichVu)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HinhThuc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HinhThuc)
        </dd>
        <dd>
            <img src="~/Content/Images/DichVu/@Model.HinhDichVu" class="img-thumbnail" style="width: 300px;height: 200px" />
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Trở về", "Index")
</p>

Areas/Admin/Views/DichVu/Edit.cshtml
@model WebNC.Models.DichVu

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>SỬA THÔNG TIN DỊCH VỤ</h2>

@using (Html.BeginForm("Edit", "DichVu", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.DichVuID)

    <div class="form-group">
        @Html.LabelFor(model => model.TenDichVu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenDichVu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenDichVu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HinhThuc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HinhThuc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HinhThuc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaDichVu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaDichVu, new { htmlAttributes = new { @min = "1", type = "number", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaDichVu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HinhDichVu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <img src="~/Content/Images/DichVu/@Model.HinhDichVu" style="height:120px; width:auto;" />
            @Html.TextBox("postedFile", "", new { @class = "input-file", type = "file" })
        </div>
    </div>
    <input hidden value="@Model.HinhDichVu" name="HinhDichVu" />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-info" style="background-color:#d9b08c" value="Lưu" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

Areas/Admin/Views/DichVu/Index.cshtml
@model IEnumerable<WebNC.Models.DichVu>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-align:center">QUẢN LÝ DỊCH VỤ</h2>
<form action="@Url.Action("Searching","DichVu")" style="text-align:right;padding-bottom:20px">
    <label>Tên dịch vụ:</label>
    <input name="tendichvu" class="form-control" style="display:inline" />
    <input id="search" type="submit" class="btn btn-info" style="background-color:#d9b08c" value="Tìm" />
</form>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenDichVu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HinhThuc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GiaDichVu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HinhDichVu)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenDichVu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HinhThuc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaDichVu)
            </td>
            <td>
                <img src="~/Content/Images/DichVu/@item.HinhDichVu" class="img-thumbnail" style="width:200px; height:200px" />
            </td>
            <td>
                <input type="button" class="btn btn-info" style="background-color:#d9b08c" value="Sửa" onclick="location.href='@Url.Action("Edit", "DichVu", new { id = item.DichVuID })'" />
                <input type="button" class="btn btn-info" style="background-color:#d9b08c" value="Chi tiết" onclick="location.href='@Url.Action("Details", "DichVu", new { id = item.DichVuID })'" />
                <input type="button" class="btn btn-info" style="background-color:#d9b08c" value="Xóa" onclick="location.href='@Url.Action("Delete", "DichVu", new { id = item.DichVuID })'" />
            </td>
        </tr>
    }
</table>
<div class="container" style="text-align:right">
    <input type="button" class="btn btn-info" style="background-color:#d9b08c" value="Thêm dịch vụ" onclick="location.href='@Url.Action("Create", "DichVu")'" />
</div>